### ISSUE TITLE
Three.JS rendering can have incorrect aspect ratio

### ISSUE THREAD

**Issue by briandrawert** [ahellander/pyurdme#129]
In an IPython notebook, when using result.display(), if the browser width changes the aspect ratio of the rendered object changes.  Also, if the width is too small or too big that aspect ratio will also be wrong.  

Possible solution: render the canvas in a div of fixed width and height.

**Comment by briandrawert** [comment]
This was fixed in StochSS:
Issue: https://github.com/StochSS/stochss/issues/201
Fix: https://github.com/StochSS/stochss/commit/7035d5d87e32c5e641701d116286385d45bda664

**Comment by ahellander** [comment]
We should pull in the change in the dev branch.
