### ISSUE TITLE
genereate_*_mesh broken with FeniCS > 1.4

### ISSUE THREAD

**Issue by ahellander** [ahellander/pyurdme#141]
Due to not using mshr. 

This is quite easy to fix, but do we need to stay compatible with Dolfin 1.4?? (should not be a problem, but a bit annoying). 

/Andreas

**Comment by briandrawert** [comment]
This seems to work in my version of 1.5 (I know there was an mid-1.5 change), but not in 1.6.

**Comment by briandrawert** [comment]
Fixed in fe6aaaf932e01887c1ad768a5677ea5dce4073f8
