### ISSUE TITLE
mshr missing from fenics ppa for ubuntu-xenial (16.04)

### ISSUE THREAD

**Issue by somathias** [ahellander/pyurdme#152]
When trying to install pyURDME on ubuntu-xenial 16.04, running the install script ./install_ubuntu.sh works fine. However, trying to run the simple diffusion example leads to an error due to the mshr package not being found. 

When checking apt-cache for mshr, nothing is found, although the fenics ppa was added which should contain the mshr package according to

https://launchpad.net/~fenics-packages/+archive/ubuntu/fenics

(sudo apt-get update was run repeatedly)

It seems that the mshr package was only added to the ppa for xenial yesterday, so it may not yet appear when searching for it using apt. I will recheck tomorrow.

**Comment by somathias** [comment]
Taking another look at the fenics ppa showed that only the mshr source package is present for ubuntu-xenial, however not the library binaries as a .deb. That's the reason why apt does not find it. 

A solution could be to manually try to install the .deb package for ubuntu-wily. Or write an email to the ppa administrator and ask him to provide the binary.

**Comment by ahellander** [comment]
I sent a question to FEniCS support:
http://fenicsproject.org/qa/9957/why-are-mshr-not-in-the-docker-containers-or-the-ppa-for-xenial

If mshr will not be a core component, we should support alternative ways to generate the built-in geometries (using Gmsh)


-------------------------------------------
Andreas Hellander
Associate Professor, Scientific Computing
Division of Scientific Computing
Department of Information Technology
Uppsala University

On Apr 27, 2016, at 8:50 AM, somathias <notifications@github.com<mailto:notifications@github.com>> wrote:


Taking another look at the fenics ppa showed that only the mshr source package is present for ubuntu-xenial, however not the library binaries as a .deb. That's the reason why apt does not find it.

A solution could be to manually try to install the .deb package for ubuntu-wily. Or write an email to the ppa administrator and ask him to provide the binary.

**Comment by ahellander** [comment]
Do you remember if they have updated the packages? Can this issue be closed?

**Comment by somathias** [comment]
Yes, the packages have been updated.
